# 예외 처리

c#에서 예외를 처리하는 방법입니다. c++과 유사한 try~catch 구문을 사용할 수 있습니다.

<br>

```c#
class Program {
    static void Main(string[] args) {
        Console.WriteLine(Division(5, 0));
        Console.WriteLine(Division(10, 2));
        Console.WriteLine(Division(3, 1));
    }
    
    static int Division(int a, int b) {
        try {
            return a / b;
        }
        catch (DivideByZeroException e) {
            Console.WriteLine(e.Message);
            return -1;
        }
    }
}
```

* try 블록 내에서 예외가 발생하면 catch 구문을 실행합니다.
* 위의 경우 발생한 예외가 DivideByZeroException이 아닌 다른 예외라면 catch 블록내의 코드를 실행하지 않습니다.

<br>

catch 블록 뒤에 finally 블록을 추가할 수 있습니다. finally 블록은 반드시 실행되는 코드입니다. 일반적으로  자원을 해제하거나 파일을 닫는 용도로 사용됩니다.

```c#
using System.IO;
// 생략

class Program {
    static void Main(string[] args) {
        StreamReader sreader = null;
        StreamWriter swriter = null;
        
        try {
            sreader = new StreamReader(File.Open("A.txt", FileMode.Open));
            swriter = new StreamWriter(File.Open("B.txt", FileMode.Append, FileAccess.Write));
            
            while (sreader.Peek() != -1)
                swriter.WriteLine(sreader.ReadLine());
        }
        catch(Exception e) {
            Console.WriteLine(e.Message);
        }
        finally {
            if (sreader != null) sreader.Close();
            if (swriter != null) swriter.Close();
        }
    }
}
```

<br>

throw를 통해서 임의로 예외를 발생시킬 수 있습니다.

```c#
class Program {
    static void Main(string[] args) {
        try {
            Console.WriteLine(Division(5, 0));
            Console.WriteLine(Division(10, 2));
            Console.WriteLine(Division(3, 1));
        }
        catch (Exception e) {
            Console.WriteLine(e.Message)
        }
    }
    
    static int Division(int a, int b) {
        if (a <= 0 || b <= 0)
            throw new Exception("0 또는 음수가 오는 것을 허용하지 않습니다.");
        else
            return a / b;
    }
}
```

